FROM python:3.7-alpine
MAINTAINER Frank Lazzarini <flazzarini@gmail.com>

ARG VERSION
EXPOSE 8000
ENV PKG=blocklister-${VERSION}-py3-none-any.whl

COPY dist/${PKG} /tmp/
RUN apk add \
    python3-dev \
    openssl
RUN pip3 install -U pip
RUN pip3 install /tmp/${PKG}
RUN pip3 install gunicorn
RUN mkdir /lists/
RUN mkdir -p /etc/blocklister/
COPY dockerfiles/blocklister.conf /etc/blocklister/

CMD ["blocklister-updater"]
